on:
  push:
  pull_request:
    branches:
    - 'main'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.0'
    - run: go test -v
